version: '3.1'

services:
  db:
    container_name: mailSender
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mailSenderDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password01
      MYSQL_ROOT_PASSWORD: Password01
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    ports:
    - 7306:3306